### ISSUE TITLE
missing code base for deepblocker

### ISSUE THREAD

**Issue by rajathpatel23** [wbsg-uni-mannheim/SC-Block#1]
Hello @abrinkmann , Thank you for the great work and excellent implementation as well. It feels there is a missing code block based on the line -  https://github.com/wbsg-uni-mannheim/SC-Block/blob/main/src/strategy/open_book/retrieval/encoding/dl_block_bi_encoder.py#L14
as well this code block

https://github.com/wbsg-uni-mannheim/SC-Block/blob/main/src/strategy/open_book/retrieval/encoding/supcon_bi_encoder.py#L6

**Comment by rajathpatel23** [comment]
I have created an PR to solve the issue faced on line - https://github.com/wbsg-uni-mannheim/SC-Block/blob/main/src/strategy/open_book/retrieval/encoding/supcon_bi_encoder.py#L6
- https://github.com/wbsg-uni-mannheim/SC-Block/pull/2

**Comment by abrinkmann** [comment]
Hello @rajathpatel23, Thank you for the pointer and the PR. I will add the "missing" code block for the deepblocker encoder latest tomorrow and will also review your PR :-)

**Comment by rajathpatel23** [comment]
Thank you @abrinkmann. I was actually thinking of adding in the PR for deepblocker code as well, great if you add it in too.

**Comment by abrinkmann** [comment]
Just added the deepblocker code. The main difference to the [original deepblocker code](https://github.com/qcri/DeepBlocker) is that we need to persist the Auto and the CTT model so that they can be used to encode query tables and index tables within the SC-Block framework. Please let me know if things are working properly.

**Comment by rajathpatel23** [comment]
@abrinkmann , closing this request - thank you for adding in the code base
