### ISSUE TITLE
missing code base to `select_source_re_ranker`

### ISSUE THREAD

**Issue by rajathpatel23** [wbsg-uni-mannheim/SC-Block#3]
- while running the end-to-end pipeline I think we have one particular class of reranking missing from the strategy directory based on the import found here - https://github.com/wbsg-uni-mannheim/SC-Block/blob/main/src/strategy/run_strategy.py#L23

**Comment by abrinkmann** [comment]
Dear @rajathpatel23 

The script 'run_strategy.py' is now up to date, so this issue should not come up again.
Please let me know if you need further assistance to run the code.

**Comment by rajathpatel23** [comment]
Thank you @abrinkmann! this is great, great work with SC-Block, the ideas here could be replicated to lot of other area which I have applied to as well

**Comment by abrinkmann** [comment]
Thank you @rajathpatel23 . I am glad that our ideas can be transferred to areas that you work on.
