### ISSUE TITLE
Unable to reproduce code

### ISSUE THREAD

**Issue by alexZeakis** [wbsg-uni-mannheim/SC-Block#4]
Hello,

I am trying to reproduce the results of your methods and I am having some issues with the code. Namely:
1) There were modules missing from the environment, like fasttext, torch, transformers, etc which had to be installed manually.
2) There were typos in the modules. For example, in 'src/finetuning/open_book/contrastive_pretraining/src/contrastive/models/modeling.py' it tries to import from 'src.finetuning.open_book.supervised_contrastive_pretraining', but in the directories it is 'src.finetuning.open_book.contrastive_pretraining'. This is noticed in other scripts as well. Also, in the 5th script it says 'python src/strategy/run_strategy', i.e. missing the suffix '.py'.
3) In each script you have hard-coded paths for the code, but you could also replace them with 'export DATA_DIR=$(pwd)/data/ export PYTHONPATH=$(pwd)' and then the user would only need to change the ES path.

While these can be easily fixed by the user as well, I have some major issues:
1) In the 4h script it says to "Please be aware that you have to train the respective models first.", but there are no instructions on how to do this. Looking at the code, I noticed that I had to provide for a path for a "model.bin", which I had from other experiments, but there could be some more details about that.
2) Finally, in the 5th script it fails when importing 'from src.similarity.coordinate import haversine'. I searched the repo in an effort to correct a typo as before, but I did not found any relevant directories.

Is it possible to fix these bugs in order to run easily the scripts and reproduce the results, end-to-end?

**Comment by abrinkmann** [comment]
Hi @alexZeakis ,

Thank you for your comments. 

I updated the repository based on your comments and added further instructions to reproduce the results.
Please let me know if you need further guidance to reproduce the results.

**Comment by abrinkmann** [comment]
Assuming that you managed to reproduce our results, I will close this issue now.
